# Generated by Django 5.1.1 on 2024-09-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'courses_names',
            },
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_courses.coursesnames'),
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('module_number', models.IntegerField(null=True)),
                ('module_description', models.CharField(max_length=400)),
                ('module_detail', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diplomado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_courses.courses')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
