# Generated by Django 5.1.1 on 2024-09-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('last_login_timetamps_unix', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('usuario', models.CharField(max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('detail_user', models.JSONField(null=True)),
                ('groups', models.ManyToManyField(related_name='userprofile_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='userprofile_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
